import type { Capability, DataScope, Role } from '../types/permissions'
import type { PageMeta } from '../types/pages'

const ADMIN: Role[] = ['timetable_administrator']
const COORD: Role[] = ['department_coordinator']
const LECT: Role[] = ['lecturer']
const FAC: Role[] = ['facilities_manager']
const STUD: Role[] = ['student']
const AUTH: Role[] = ['unauthenticated']

function page(
  id: string,
  title: string,
  purpose: string,
  route: string,
  referenceFile: string,
  width: number,
  height: number,
  roles: Role[],
  phase: number,
  capabilities: Capability[],
  scope: DataScope,
): PageMeta {
  return {
    id,
    title,
    purpose,
    route,
    referenceFile,
    width,
    height,
    roles,
    phase,
    capabilities,
    scope,
  }
}

export const pageInventory: PageMeta[] = [
  page(
    'auth-login',
    'Login',
    'Secure entry for students and staff using email, ID or institutional sign-in.',
    '/auth/login',
    '01_Authentication/login.png',
    1182,
    1144,
    AUTH,
    2,
    ['view'],
    'public',
  ),
  page(
    'auth-forgot-password',
    'Forgot Password',
    'Starts account recovery with an email or university identifier.',
    '/auth/forgot-password',
    '01_Authentication/forgot-password.png',
    778,
    924,
    AUTH,
    2,
    ['view'],
    'public',
  ),
  page(
    'auth-verify-email',
    'Verify Email',
    'Confirms recovery or verification and allows the message to be resent.',
    '/auth/verify-email',
    '01_Authentication/verify-email.png',
    778,
    924,
    AUTH,
    2,
    ['view'],
    'public',
  ),
  page(
    'auth-reset-password',
    'Reset Password',
    'Lets the user set and confirm a new password after identity verification.',
    '/auth/reset-password',
    '01_Authentication/reset-password.png',
    778,
    924,
    AUTH,
    2,
    ['view'],
    'public',
  ),
  page(
    'auth-reset-success',
    'Reset Successful',
    'Closes recovery and returns the user to sign-in.',
    '/auth/reset-success',
    '01_Authentication/reset-success.png',
    780,
    924,
    AUTH,
    2,
    ['view'],
    'public',
  ),
  page(
    'admin-dashboard',
    'Dashboard',
    'University-wide status, conflicts, disruptions, utilisation and shortcuts to generation, repair and publishing.',
    '/admin/dashboard',
    '02_Timetable_Admin/dashboard.png',
    1600,
    1000,
    ADMIN,
    0,
    ['view', 'generate'],
    'university',
  ),
  page(
    'admin-academic-sessions',
    'Academic Sessions',
    'Creates and activates academic sessions, semesters and scheduling windows used by the solver.',
    '/admin/academic-sessions',
    '02_Timetable_Admin/academic-sessions.png',
    1600,
    1000,
    ADMIN,
    3,
    ['view', 'edit'],
    'university',
  ),
  page(
    'admin-faculties-departments',
    'Faculties & Departments',
    'Models university structure and assigns departmental responsibility for timetable data.',
    '/admin/faculties-departments',
    '02_Timetable_Admin/faculties-departments.png',
    1600,
    1000,
    ADMIN,
    3,
    ['view', 'edit'],
    'university',
  ),
  page(
    'admin-courses',
    'Courses',
    'Maintains the course catalogue including level, duration, expected size and room requirements.',
    '/admin/courses',
    '02_Timetable_Admin/courses.png',
    1600,
    1000,
    ADMIN,
    3,
    ['view', 'edit'],
    'university',
  ),
  page(
    'admin-student-cohorts',
    'Student Cohorts',
    'Defines student groups that must not be scheduled into overlapping required classes.',
    '/admin/student-cohorts',
    '02_Timetable_Admin/student-cohorts.png',
    1600,
    1000,
    ADMIN,
    3,
    ['view', 'edit'],
    'university',
  ),
  page(
    'admin-lecturers',
    'Lecturers',
    'Maintains lecturer records, workload and availability used by the solver.',
    '/admin/lecturers',
    '02_Timetable_Admin/lecturers.png',
    1600,
    1000,
    ADMIN,
    3,
    ['view', 'edit'],
    'university',
  ),
  page(
    'admin-rooms-facilities',
    'Rooms & Facilities',
    'Maintains schedulable rooms, capacities, types, equipment and availability.',
    '/admin/rooms-facilities',
    '02_Timetable_Admin/rooms-facilities.png',
    1600,
    1000,
    ADMIN,
    3,
    ['view', 'edit'],
    'university',
  ),
  page(
    'admin-course-assignments',
    'Course Assignments',
    'Links courses to lecturers and cohorts so the solver knows who must attend each class.',
    '/admin/course-assignments',
    '02_Timetable_Admin/course-assignments.png',
    1600,
    1000,
    ADMIN,
    3,
    ['view', 'edit'],
    'university',
  ),
  page(
    'admin-scheduling-constraints',
    'Scheduling Constraints',
    'Defines hard rules that cannot be broken and soft preferences the optimiser should try to satisfy.',
    '/admin/scheduling-constraints',
    '02_Timetable_Admin/scheduling-constraints.png',
    1600,
    1000,
    ADMIN,
    4,
    ['view', 'edit'],
    'university',
  ),
  page(
    'admin-constraint-weights',
    'Constraint Weights',
    'Controls how strongly the solver values stability, gaps and room efficiency.',
    '/admin/constraint-weights',
    '02_Timetable_Admin/constraint-weights.png',
    1600,
    1000,
    ADMIN,
    4,
    ['view', 'edit'],
    'university',
  ),
  page(
    'admin-generate-timetable',
    'Generate Timetable',
    'Configures and launches optimisation for a selected scheduling period.',
    '/admin/generate-timetable',
    '02_Timetable_Admin/generate-timetable.png',
    1600,
    1000,
    ADMIN,
    5,
    ['view', 'generate'],
    'university',
  ),
  page(
    'admin-generation-results',
    'Generation Results',
    'Shows whether a feasible solution was found and summarises conflicts, penalties and runtime.',
    '/admin/generation-results',
    '02_Timetable_Admin/generation-results.png',
    1600,
    1000,
    ADMIN,
    5,
    ['view'],
    'university',
  ),
  page(
    'admin-master-timetable',
    'Master Timetable',
    'Institution-wide timetable with filters for departments, cohorts, lecturers and rooms.',
    '/admin/master-timetable',
    '02_Timetable_Admin/master-timetable.png',
    1600,
    1000,
    ADMIN,
    5,
    ['view'],
    'university',
  ),
  page(
    'admin-conflict-monitor',
    'Conflict Monitor',
    'Surfaces room, lecturer, cohort, capacity and availability violations.',
    '/admin/conflict-monitor',
    '02_Timetable_Admin/conflict-monitor.png',
    1600,
    1000,
    ADMIN,
    5,
    ['view'],
    'university',
  ),
  page(
    'admin-disruption-centre',
    'Disruption Centre',
    'Central place for room closures and lecturer unavailability after publication.',
    '/admin/disruption-centre',
    '02_Timetable_Admin/disruption-centre.png',
    1600,
    1000,
    ADMIN,
    7,
    ['view', 'reportDisruption'],
    'university',
  ),
  page(
    'admin-repair-timetable',
    'Repair Timetable',
    'Runs the repair engine against a selected disruption while preserving unaffected assignments.',
    '/admin/repair-timetable',
    '02_Timetable_Admin/repair-timetable.png',
    1600,
    1000,
    ADMIN,
    8,
    ['view', 'approveRepair'],
    'university',
  ),
  page(
    'admin-repair-comparison',
    'Repair Comparison',
    'Compares repair solutions using moved classes, conflicts, penalties and preservation.',
    '/admin/repair-comparison',
    '02_Timetable_Admin/repair-comparison.png',
    1600,
    1000,
    ADMIN,
    8,
    ['view', 'approveRepair'],
    'university',
  ),
  page(
    'admin-change-review',
    'Change Review',
    'Shows exactly what will change before a repair is accepted and published.',
    '/admin/change-review',
    '02_Timetable_Admin/change-review.png',
    1600,
    1000,
    ADMIN,
    6,
    ['view', 'approveRepair', 'publish'],
    'university',
  ),
  page(
    'admin-publish-timetable',
    'Publish Timetable',
    'Approves the selected timetable version and makes it available to the university.',
    '/admin/publish-timetable',
    '02_Timetable_Admin/publish-timetable.png',
    1600,
    1000,
    ADMIN,
    6,
    ['view', 'publish'],
    'university',
  ),
  page(
    'admin-timetable-versions',
    'Timetable Versions',
    'Keeps a history of published and draft versions for traceability and comparison.',
    '/admin/timetable-versions',
    '02_Timetable_Admin/timetable-versions.png',
    1600,
    1000,
    ADMIN,
    6,
    ['view'],
    'university',
  ),
  page(
    'admin-reports-analytics',
    'Reports & Analytics',
    'Measures utilisation, workload, stability, conflicts and repair performance.',
    '/admin/reports-analytics',
    '02_Timetable_Admin/reports-analytics.png',
    1600,
    1000,
    ADMIN,
    10,
    ['view'],
    'university',
  ),
  page(
    'admin-users-roles',
    'Users & Roles',
    'Controls accounts and role-based permissions.',
    '/admin/users-roles',
    '02_Timetable_Admin/users-roles.png',
    1600,
    1000,
    ADMIN,
    9,
    ['view', 'edit'],
    'university',
  ),
  page(
    'admin-audit-log',
    'Audit Log',
    'Records who changed what and when for scheduling decisions.',
    '/admin/audit-log',
    '02_Timetable_Admin/audit-log.png',
    1600,
    1000,
    ADMIN,
    10,
    ['view'],
    'university',
  ),
  page(
    'admin-notifications',
    'Notifications',
    'Collects administrator alerts for timetable changes, approvals, disruptions and deadlines.',
    '/admin/notifications',
    '02_Timetable_Admin/notifications.png',
    1600,
    1000,
    ADMIN,
    10,
    ['view'],
    'university',
  ),
  page(
    'admin-settings',
    'Settings',
    'Stores administrator preferences and application configuration.',
    '/admin/settings',
    '02_Timetable_Admin/settings.png',
    1600,
    1000,
    ADMIN,
    9,
    ['view', 'edit'],
    'university',
  ),
  page(
    'admin-help-support',
    'Help & Support',
    'Explains administrator workflows and provides a route for assistance.',
    '/admin/help-support',
    '02_Timetable_Admin/help-support.png',
    1600,
    1000,
    ADMIN,
    9,
    ['view'],
    'university',
  ),
  page(
    'coordinator-dashboard',
    'Dashboard',
    'Department-level courses, cohorts, assignments, pending requests and timetable issues.',
    '/coordinator/dashboard',
    '03_Department_Coordinator/dashboard.png',
    1600,
    1000,
    COORD,
    9,
    ['view'],
    'department',
  ),
  page(
    'coordinator-department-courses',
    'Department Courses',
    'Lets the coordinator maintain courses owned by their department.',
    '/coordinator/department-courses',
    '03_Department_Coordinator/department-courses.png',
    1600,
    1000,
    COORD,
    9,
    ['view', 'edit'],
    'department',
  ),
  page(
    'coordinator-course-assignments',
    'Course Assignments',
    'Links department courses to lecturers and cohorts.',
    '/coordinator/course-assignments',
    '03_Department_Coordinator/course-assignments.png',
    1600,
    1000,
    COORD,
    9,
    ['view', 'edit'],
    'department',
  ),
  page(
    'coordinator-student-cohorts',
    'Student Cohorts',
    'Defines departmental student groups that must not overlap in required classes.',
    '/coordinator/student-cohorts',
    '03_Department_Coordinator/student-cohorts.png',
    1600,
    1000,
    COORD,
    9,
    ['view', 'edit'],
    'department',
  ),
  page(
    'coordinator-lecturer-availability',
    'Lecturer Availability',
    'Shows submitted availability for departmental lecturers and missing information.',
    '/coordinator/lecturer-availability',
    '03_Department_Coordinator/lecturer-availability.png',
    1600,
    1000,
    COORD,
    9,
    ['view'],
    'department',
  ),
  page(
    'coordinator-department-constraints',
    'Department Constraints',
    'Captures local lab needs or preferred and blocked teaching periods.',
    '/coordinator/department-constraints',
    '03_Department_Coordinator/department-constraints.png',
    1600,
    1000,
    COORD,
    9,
    ['view', 'edit'],
    'department',
  ),
  page(
    'coordinator-scheduling-requests',
    'Scheduling Requests',
    'Lets the department request room changes, extra classes or reassignment.',
    '/coordinator/scheduling-requests',
    '03_Department_Coordinator/scheduling-requests.png',
    1600,
    1000,
    COORD,
    9,
    ['view', 'submitRequest'],
    'department',
  ),
  page(
    'coordinator-department-timetable',
    'Department Timetable',
    'Displays only the department timetable for review.',
    '/coordinator/department-timetable',
    '03_Department_Coordinator/department-timetable.png',
    1600,
    1000,
    COORD,
    9,
    ['view'],
    'department',
  ),
  page(
    'coordinator-conflict-review',
    'Conflict Review',
    'Focuses the coordinator on conflicts affecting their own courses and cohorts.',
    '/coordinator/conflict-review',
    '03_Department_Coordinator/conflict-review.png',
    1600,
    1000,
    COORD,
    9,
    ['view'],
    'department',
  ),
  page(
    'coordinator-change-requests',
    'Change Requests',
    'Tracks timetable-change requests and approval status.',
    '/coordinator/change-requests',
    '03_Department_Coordinator/change-requests.png',
    1600,
    1000,
    COORD,
    9,
    ['view', 'submitRequest'],
    'department',
  ),
  page(
    'coordinator-reports-analytics',
    'Reports & Analytics',
    'Departmental utilisation, workload, conflicts and request metrics.',
    '/coordinator/reports-analytics',
    '03_Department_Coordinator/reports-analytics.png',
    1600,
    1000,
    COORD,
    10,
    ['view'],
    'department',
  ),
  page(
    'coordinator-notifications',
    'Notifications',
    'Coordinator alerts for requests, conflicts and timetable changes.',
    '/coordinator/notifications',
    '03_Department_Coordinator/notifications.png',
    1600,
    1000,
    COORD,
    10,
    ['view'],
    'department',
  ),
  page(
    'coordinator-profile',
    'Profile',
    'Stores the coordinator identity, role and department details.',
    '/coordinator/profile',
    '03_Department_Coordinator/profile.png',
    1600,
    1000,
    COORD,
    9,
    ['view', 'edit'],
    'department',
  ),
  page(
    'coordinator-settings',
    'Settings',
    'Coordinator preferences without university-wide administrative controls.',
    '/coordinator/settings',
    '03_Department_Coordinator/settings.png',
    1600,
    1000,
    COORD,
    9,
    ['view', 'edit'],
    'department',
  ),
  page(
    'coordinator-help-support',
    'Help & Support',
    'Explains coordinator workflows and how to request help.',
    '/coordinator/help-support',
    '03_Department_Coordinator/help-support.png',
    1600,
    1000,
    COORD,
    9,
    ['view'],
    'department',
  ),
  page(
    'lecturer-dashboard',
    'Dashboard',
    'Personal teaching workload, next classes, availability and recent timetable changes.',
    '/lecturer/dashboard',
    '04_Lecturer/dashboard.png',
    1600,
    1000,
    LECT,
    9,
    ['view'],
    'personal',
  ),
  page(
    'lecturer-my-timetable',
    'My Timetable',
    'The lecturer’s personal weekly teaching schedule.',
    '/lecturer/my-timetable',
    '04_Lecturer/my-timetable.png',
    1600,
    1000,
    LECT,
    9,
    ['view'],
    'personal',
  ),
  page(
    'lecturer-my-courses',
    'My Courses',
    'Lists courses assigned to the lecturer.',
    '/lecturer/my-courses',
    '04_Lecturer/my-courses.png',
    1600,
    1000,
    LECT,
    9,
    ['view'],
    'personal',
  ),
  page(
    'lecturer-availability',
    'Availability',
    'Lets a lecturer state recurring periods when they can or cannot teach.',
    '/lecturer/availability',
    '04_Lecturer/availability.png',
    1600,
    1000,
    LECT,
    4,
    ['view', 'edit'],
    'personal',
  ),
  page(
    'lecturer-scheduling-preferences',
    'Scheduling Preferences',
    'Captures preferred periods or avoidance of excessive back-to-back classes as soft constraints.',
    '/lecturer/scheduling-preferences',
    '04_Lecturer/scheduling-preferences.png',
    1600,
    1000,
    LECT,
    4,
    ['view', 'edit'],
    'personal',
  ),
  page(
    'lecturer-report-unavailability',
    'Report Unavailability',
    'Lets a lecturer report temporary absence after scheduling; this can become a disruption.',
    '/lecturer/report-unavailability',
    '04_Lecturer/report-unavailability.png',
    1600,
    1000,
    LECT,
    7,
    ['view', 'reportDisruption'],
    'personal',
  ),
  page(
    'lecturer-change-requests',
    'Change Requests',
    'Tracks the lecturer’s timetable-change requests and their approval status.',
    '/lecturer/change-requests',
    '04_Lecturer/change-requests.png',
    1600,
    1000,
    LECT,
    9,
    ['view', 'submitRequest'],
    'personal',
  ),
  page(
    'lecturer-timetable-changes',
    'Timetable Changes',
    'Shows before and after schedule changes that affect the lecturer.',
    '/lecturer/timetable-changes',
    '04_Lecturer/timetable-changes.png',
    1600,
    1000,
    LECT,
    9,
    ['view'],
    'personal',
  ),
  page(
    'lecturer-notifications',
    'Notifications',
    'Lecturer alerts for timetable changes, approvals and deadlines.',
    '/lecturer/notifications',
    '04_Lecturer/notifications.png',
    1600,
    1000,
    LECT,
    10,
    ['view'],
    'personal',
  ),
  page(
    'lecturer-profile',
    'Profile',
    'Stores the lecturer’s identity, role and department details.',
    '/lecturer/profile',
    '04_Lecturer/profile.png',
    1600,
    1000,
    LECT,
    9,
    ['view', 'edit'],
    'personal',
  ),
  page(
    'lecturer-settings',
    'Settings',
    'Lecturer notification and display preferences.',
    '/lecturer/settings',
    '04_Lecturer/settings.png',
    1600,
    1000,
    LECT,
    9,
    ['view', 'edit'],
    'personal',
  ),
  page(
    'lecturer-help-support',
    'Help & Support',
    'Explains lecturer workflows and how to get help.',
    '/lecturer/help-support',
    '04_Lecturer/help-support.png',
    1600,
    1000,
    LECT,
    9,
    ['view'],
    'personal',
  ),
  page(
    'facilities-dashboard',
    'Dashboard',
    'Room availability, maintenance, active disruptions and facility workload.',
    '/facilities/dashboard',
    '05_Facilities_Manager/dashboard.png',
    1600,
    1000,
    FAC,
    9,
    ['view'],
    'university',
  ),
  page(
    'facilities-rooms',
    'Rooms',
    'Inventory of teaching spaces with capacity, type, equipment and current status.',
    '/facilities/rooms',
    '05_Facilities_Manager/rooms.png',
    1600,
    1000,
    FAC,
    3,
    ['view', 'edit'],
    'university',
  ),
  page(
    'facilities-add-edit-room',
    'Add / Edit Room',
    'Creates or updates room details that determine whether a space can satisfy a class.',
    '/facilities/rooms/edit',
    '05_Facilities_Manager/add-edit-room.png',
    1600,
    1000,
    FAC,
    3,
    ['view', 'edit'],
    'university',
  ),
  page(
    'facilities-room-availability',
    'Room Availability',
    'Defines recurring or temporary windows when a room can be scheduled.',
    '/facilities/room-availability',
    '05_Facilities_Manager/room-availability.png',
    1600,
    1000,
    FAC,
    4,
    ['view', 'edit'],
    'university',
  ),
  page(
    'facilities-room-status',
    'Room Status',
    'Operational view of rooms that are available, unavailable, closed or under maintenance.',
    '/facilities/room-status',
    '05_Facilities_Manager/room-status.png',
    1600,
    1000,
    FAC,
    7,
    ['view', 'edit'],
    'university',
  ),
  page(
    'facilities-report-disruption',
    'Report Disruption',
    'Records a room outage or closure with its time window and reason.',
    '/facilities/report-disruption',
    '05_Facilities_Manager/report-disruption.png',
    1600,
    1000,
    FAC,
    7,
    ['view', 'reportDisruption'],
    'university',
  ),
  page(
    'facilities-affected-classes',
    'Affected Classes',
    'Shows classes, lecturers and cohorts that depend on a disrupted room.',
    '/facilities/affected-classes',
    '05_Facilities_Manager/affected-classes.png',
    1600,
    1000,
    FAC,
    7,
    ['view'],
    'university',
  ),
  page(
    'facilities-maintenance-schedule',
    'Maintenance Schedule',
    'Plans room closures in advance so the scheduler can avoid unavailable facilities.',
    '/facilities/maintenance-schedule',
    '05_Facilities_Manager/maintenance-schedule.png',
    1600,
    1000,
    FAC,
    7,
    ['view', 'edit', 'reportDisruption'],
    'university',
  ),
  page(
    'facilities-room-utilization',
    'Room Utilization',
    'Measures how effectively teaching spaces are used.',
    '/facilities/room-utilization',
    '05_Facilities_Manager/room-utilization.png',
    1600,
    1000,
    FAC,
    10,
    ['view'],
    'university',
  ),
  page(
    'facilities-facility-history',
    'Facility History',
    'Record of room incidents, maintenance and availability changes.',
    '/facilities/facility-history',
    '05_Facilities_Manager/facility-history.png',
    1600,
    1000,
    FAC,
    10,
    ['view'],
    'university',
  ),
  page(
    'facilities-notifications',
    'Notifications',
    'Facilities alerts for disruptions, maintenance and affected classes.',
    '/facilities/notifications',
    '05_Facilities_Manager/notifications.png',
    1600,
    1000,
    FAC,
    10,
    ['view'],
    'university',
  ),
  page(
    'facilities-profile',
    'Profile',
    'Stores the facilities manager identity and role details.',
    '/facilities/profile',
    '05_Facilities_Manager/profile.png',
    1600,
    1000,
    FAC,
    9,
    ['view', 'edit'],
    'university',
  ),
  page(
    'facilities-settings',
    'Settings',
    'Facilities manager preferences and notification settings.',
    '/facilities/settings',
    '05_Facilities_Manager/settings.png',
    1600,
    1000,
    FAC,
    9,
    ['view', 'edit'],
    'university',
  ),
  page(
    'facilities-help-support',
    'Help & Support',
    'Explains facilities workflows and how to get help.',
    '/facilities/help-support',
    '05_Facilities_Manager/help-support.png',
    1600,
    1000,
    FAC,
    9,
    ['view'],
    'university',
  ),
  page(
    'student-dashboard',
    'Dashboard',
    'Today’s classes, next class, timetable changes and announcements.',
    '/student/dashboard',
    '06_Student/dashboard.png',
    1586,
    992,
    STUD,
    9,
    ['view'],
    'personal',
  ),
  page(
    'student-my-timetable',
    'My Timetable',
    'Personal weekly class schedule with times, rooms and free periods.',
    '/student/my-timetable',
    '06_Student/my-timetable.png',
    1586,
    992,
    STUD,
    9,
    ['view'],
    'personal',
  ),
  page(
    'student-todays-schedule',
    "Today's Schedule",
    'Day view of classes, free periods, rooms and immediate changes.',
    '/student/today',
    '06_Student/todays-schedule.png',
    1586,
    992,
    STUD,
    9,
    ['view'],
    'personal',
  ),
  page(
    'student-course-schedule',
    'Course Schedule',
    'When and where each registered course meets.',
    '/student/course-schedule',
    '06_Student/course-schedule.png',
    1586,
    992,
    STUD,
    9,
    ['view'],
    'personal',
  ),
  page(
    'student-timetable-changes',
    'Timetable Changes',
    'Before and after schedule changes that affect the student.',
    '/student/timetable-changes',
    '06_Student/timetable-changes.png',
    1586,
    992,
    STUD,
    9,
    ['view'],
    'personal',
  ),
  page(
    'student-notifications',
    'Notifications',
    'Student alerts for timetable changes that affect registered courses.',
    '/student/notifications',
    '06_Student/notifications.png',
    1586,
    992,
    STUD,
    10,
    ['view'],
    'personal',
  ),
]

export function getPageById(id: string): PageMeta | undefined {
  return pageInventory.find((item) => item.id === id)
}

export function getPreviewHref(pageId: string): string {
  if (pageId === 'admin-dashboard') {
    return '/preview/admin/dashboard'
  }
  return `/preview/unavailable/${pageId}`
}

const PHASE3_ADMIN_PAGES = new Set([
  'admin-academic-sessions',
  'admin-faculties-departments',
  'admin-courses',
  'admin-student-cohorts',
  'admin-lecturers',
  'admin-rooms-facilities',
  'admin-course-assignments',
])

const PHASE4_PAGES = new Set([
  'admin-scheduling-constraints',
  'admin-constraint-weights',
  'lecturer-availability',
  'lecturer-scheduling-preferences',
  'facilities-room-availability',
])

const PHASE5_PAGES = new Set([
  'admin-generate-timetable',
  'admin-generation-results',
  'admin-master-timetable',
  'admin-conflict-monitor',
])

const PHASE6_PAGES = new Set([
  'admin-publish-timetable',
  'admin-timetable-versions',
  'admin-change-review',
])

export function getAppHref(pageId: string): string {
  const page = getPageById(pageId)
  if (!page) {
    return `/unavailable/${pageId}`
  }
  if (
    pageId.endsWith('-dashboard') ||
    PHASE3_ADMIN_PAGES.has(pageId) ||
    PHASE4_PAGES.has(pageId) ||
    PHASE5_PAGES.has(pageId) ||
    PHASE6_PAGES.has(pageId)
  ) {
    return page.route
  }
  return `/unavailable/${pageId}`
}
